pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604

stages:
  - stage: GitClone
    jobs:
      - job: 'Credentials'
        steps:
          - bash: 'echo This is Credentials Step'
  - stage: MavenBuild
    jobs:
      - job: 'ConePull'
        steps:
          - bash: 'echo This is Credentials Step'

