pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604

stages:
  - stage: 'Build'
    jobs:
      - job: Kashvi
        steps:
          - bash: echo "Welcome to Kashvi"
      - job: Hari
        steps:
          - bash: echo "Welcome to Hari"

