trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven app/pom.xml'
  inputs:
    mavenPomFile: 'app/pom.xml'
    codeCoverageToolOption: Cobertura