pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604

stages:
  
  - stage: MavenBuild
    jobs:
      - job: 'BuildCode'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'app/pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
  - stage: PublishArtifacts
    jobs:
      - job: 'CopyFiles'
        steps:
          - task: CopyFiles@2
            inputs:
              Contents: '**/*.jar'
              TargetFolder: '$(build.artifactstagingdirectory)'
          

