trigger:
- master

variables:

  # Web app name
  webAppName: 'java-spring-boot'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: 'Build'
    jobs:
      - job: "One"
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo Running Script 1'