trigger:
- master
variables:
  appName: "javahome"

stages:
  - stage: 'Build'
    jobs:
      - job: One
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'app/pom.xml'
            goals: 'clean package'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            testRunTitle: 'Junit Test'
            codeCoverageToolOption: 'JaCoCo'
            codeCoverageFailIfEmpty: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false