trigger:
- master

variables:

  # Web app name
  webAppName: 'java-spring-boot'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: 'Build'
    jobs:
      - job: "One"
        steps:
          - task: Bash@3
            displayName: "Run Script 1"
            inputs:
              script: |
                echo "Running Script 1"